version: "3.7"
services:
  server:
    image: ngrok-server-example:latest
    ports:
      - 5000:5000
  ngrok:
    image: ngrok/ngrok:alpine # imagem para raspberry pi
    ports:
      - 4040:4040
    volumes:
      - ./ngrok-config.yml:/var/lib/ngrok/ngrok.ymlåå
    depends_on:
      - server