server:
  image: server:latest
  ports:
    - 5000:5000
# ngrok:
#   image: wernight/ngrok:latest
#   ports:
#     - 4040:4040
#   environment:
#     NGROK_PROTOCOL: http
#     NGROK_PORT: server:5000
#     NGROK_AUTH: 
#   depends_on:
#     - serverdock